#!/bin/sh

deploy_to=`cat DEPLOY_TO`

ssh as2 <<EOF
cd ${deploy_to}/current
/usr/local/go/bin/go build -o shroty
killll -INT shroty
cd ${deploy_to}/current
nohup ./shroty &
print $! > ${deploy_to}/shared/pids/shroty.pid
EOF
